@startuml
skinparam packageStyle rectangle
skinparam componentStyle rectangle
skinparam ClassBackgroundColor #93C47D
skinparam ClassBorderColor #38761D
skinparam DefaultTextAlignment center
hide circle
skinparam arrowThickness 1.1
skinparam classAttributeIconSize 0

package "UI Component" {
    class "«static»\nUi" as Ui {
        + readCommand() : String
        + showWelcome() : void
        + showApplicationList(...) : void
        + showSearchResults(...) : void
        + showApplicationEdited(...) : void
        + showError(...) : void
    }
}

package "App Component" as AppLogic #FFFFFF {
    class "CommandRunner" as CommandRunner #EEEEEE
    class "JobPilot" as JobPilot #EEEEEE
}

package "Parser Component" as ParserLogic #FFFFFF {
    class "Parser" as Parser #EEEEEE
}

package "Task Component" as Model #FFFFFF {
    class "Application" as Application #EEEEEE
    class "IndustryTag" as IndustryTag #EEEEEE
    class "Filterer" as Filterer #EEEEEE
}

' Incoming dependencies to UI
JobPilot .down.> Ui : reads input via >
CommandRunner .right.> Ui : invokes display methods >
Parser .down.> Ui : invokes showError() >
Filterer .up.> Ui : invokes showFilterResults() >

' Outgoing dependencies from UI
Ui .down.> Application : formats data for output >
Ui .down.> IndustryTag : formats data for output >

@enduml