@startuml
skinparam ParticipantBackgroundColor #white
skinparam ActorBackgroundColor #white
skinparam NoteBackgroundColor #white
skinparam LifeLineBackgroundColor #white
skinparam ArrowColor #black
skinparam SequenceMessageAlign center

actor User as user
participant ":Ui" as ui
participant ":Parser" as parser
participant ":DeleterParser" as delParser
participant ":CommandRunner" as runner
participant ":Deleter" as del
participant "applications\n:ArrayList" as apps

note right of user
    Note: arrows pointing
    towards the left edge
    point to app.JobPilot.
end note

user -> ui : "delete 2"
activate ui
return input

-> parser : parse("delete 2")
activate parser

parser -> delParser : parse("delete 2")
activate delParser
return cmd:ParsedCommand

return cmd:ParsedCommand

-> runner : run(cmd)
activate runner

runner -> del : deleteApplication(applications, 1)
activate del

del -> apps : remove(1)
activate apps
return removed:Application

return removed:Application

runner -> ui : showApplicationDeleted(removed, size)
activate ui
ui --> user : prints confirmation message
return

return continueFlag:boolean
@enduml