\@startuml
 skinparam packageStyle rectangle
 skinparam ClassBackgroundColor #bfa060
 skinparam ClassBorderColor #6e5927
 skinparam ArrowColor #6e5927
 skinparam StereotypeCBackgroundColor #bfa060
 hide circle
 skinparam arrowThickness 1.1
 skinparam classAttributeIconSize 0

 package "Storage Component" <<Rectangle>> #FFFFFF {
     class "Storage" as Storage {
         - {static} LOGGER : Logger
         - {static} CURRENT_WORKING_DIRECTORY : String
         - {static} FILE : File
         - gson : Gson
         - jobPilotDataFile : File
         + Storage()
         - ensureFileExists() : void
         + loadFromFile() : ArrayList<Application>
         + saveToFile(applications : ArrayList<Application>) : void
     }
 }

 package "Task Component" as Model #FFFFFF {
     class Application #EEEEEE
     class IndustryTag #EEEEEE
 }

 rectangle "com.google.gson" as GsonLib #FFFFFF {
     class Gson #EEEEEE
 }

 rectangle "java.io / java.nio" as Support #FFFFFF {
     class File #EEEEEE
     class FileReader #EEEEEE
     class FileWriter #EEEEEE
 }

 Storage .left.> Support : uses for file I/O >
 Storage .right.> GsonLib : uses for JSON parsing >
 Storage .down.> Model : serializes/deserializes >

 Storage -[hidden]- Model
 @enduml